version: '3'

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
    env_file:
      - ./.env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dream-diary-network
  backend:
    image: ${BACKEND_IMAGE}
    restart: always
    depends_on:
      - mysql
    env_file:
      - ./.env
    expose:
      - 5000
    networks:
      - dream-diary-network

volumes:
  mysql_data:

networks:
  dream-diary-network:
    external: true
